remote_theme: pmarsceill/just-the-docs
title: Viget Base Craft Module
color_scheme: dark
footer_content: "Copyright &copy; 2021 Viget Labs"
aux_links:
  "Github Repo":
    - "//github.com/vigetlabs/craft-viget-base"
